name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo fmt --check
    - name: Build debug
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
